### ISSUE TITLE
Add advanced search functionality

### ISSUE THREAD

**Issue by oguzaydinn** [Aell-a/swe573-project#12]
Users should be able to search mystery objects by it's basic properties or tags. 
Ex. "Yellow, 30 grams, circular"

**Comment by lattaai13** [comment]
Hello, I tried to solve the issue.

This is what I did:

Implemented search functionality for mystery objects based on their basic properties (color, weight, shape) and tags. Added a new endpoint in PostController, a new method in PostService, and a custom query in PostRepository to support this feature.

You can review changes in this commit: https://github.com/lattaai13/Aell-a-swe573-project-12/commit/5d884fbc47b787f04319f5ccb994d01db914fec6.


> [!CAUTION]
> Disclaimer: The commit was created by Latta AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---
This issue was tried to solve for free by Latta AI - https://latta.ai/ourmission

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.

**Comment by oguzaydinn** [comment]
Implemented advanced search functionality on backend at 00f83b0 and on frontend at 6f659da.
